# Generated by Django 5.0.4 on 2024-04-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiped',
            options={'get_latest_by': 'dtime'},
        ),
    ]
